name: Orchestrate Actions on Push

on: [push]

jobs:
  install-vendor:
    uses: ./.github/workflows/install-vendor.yml
  run-unit-tests:
    needs: install-vendor
    uses: ./.github/workflows/run-unit-tests.yml
    with:
      vendor-cache-keys: ${{ needs.install-vendor.outputs.cache-keys }}
  test-client-package:
    needs: install-vendor
    uses: ./.github/workflows/test-package.yml
    with:
      vendor-cache-keys: ${{ needs.install-vendor.outputs.cache-keys }}
      package-name: html_forms
  test-server-package:
    needs: install-vendor
    uses: ./.github/workflows/test-package.yml
    with:
      vendor-cache-keys: ${{ needs.install-vendor.outputs.cache-keys }}
      package-name: html_forms_server
