name: Push Tests

on: [push]

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install Vendor Libraries
        uses: ./.github/workflows/install-vendor.yml
        with:
          runs-on: ${{ runner.os }}
      - name: Restore Vendor
        id: restore-vendor
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-${{ hashFiles('script/install-*.sh', 'script/util.sh') }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm ci
      - run: node make.mjs test
