name: Test Package

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      vendor-cache-keys:
        required: true
        type: string

jobs:
  package:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore Vendor
        id: restore-vendor
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ fromJSON(inputs.vendor-cache-keys)[runner.os] }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm ci
      - run: node make.mjs dist-${{ inputs.package-name }}
      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.package-name }}-tarball
          path: build/${{ inputs.package-name }}-*.tgz
