name: Test Package

on:
  workflow_call:
    inputs:
      vendor-cache-keys:
        required: true
        type: string
      client-artifact:
        required: true
        type: string
      server-artifact:
        required: true
        type: string

jobs:
  test-package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Restore Vendor
        id: restore-vendor
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ fromJSON(inputs.vendor-cache-keys)[runner.os] }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm ci
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.client-artifact }}
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.server-artifact }}
      - run: script/test-release.sh html_forms-*.tgz
      # Note above client must happen before below server
      # because server depends on client being installed
      - run: script/test-release.sh html_forms_server-*.tgz
