name: Push Tests

on: [push]

jobs:
  install-boost:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Cache Boost
        id: cache-boost
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-boost-${{ hashFiles('script/install-boost.sh', 'script/util.sh') }}
      - if: ${{ steps.cache-boost.outputs.cache-hit != 'true' }}
        name: Install Boost
        run: script/install-boost.sh
  unit-tests:
    needs: install-boost
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - name: Restore Boost
        id: restore-boost
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-boost-${{ hashFiles('script/install-boost.sh', 'script/util.sh') }}
      - if: ${{ steps.restore-boost.outputs.cache-hit != 'true' }}
        name: Report Failure
        run: |
          echo "Boost cache failed to restore"
          exit 1
      - uses: actions/checkout@v4
      - name: Install libarchive
        run: script/install-libarchive.sh
      - name: Install Lighter Dependencies
        run: script/install-deps.sh
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm ci
      - run: node make.mjs test
